// teacher-ui/src/components/layout/sidebar.vue
<script setup lang="ts">
import {RouterLink} from "vue-router";
import {data} from './sidebarData';
const navData = data('1234')
</script>
<template>
   <div class="bg-gray-900 text-white lg:fixed top-0 left-0 z-[50] w-[250px] h-screen flex flex-col gap-4 p-4 md:p-6 lg:p-8">
        <RouterLink to="#" className="flex items-center gap-2">
          <span class='py-3  tracking-tighter text-2xl  font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 via-indigo-500 to-purple-500'>Code Tutor</span>
        </RouterLink>
    <nav className="flex flex-col gap-2">
          <template v-for="{text, icon: Icon, link} in navData" :key='text'>
            <RouterLink :to='link' class='flex items-center gap-2 hover:bg-gray-800 px-3 py-2 rounded-md'>
              <component :is="Icon"/>
              <span> {{text}} </span>
            </RouterLink>
        </template>
        </nav>
      </div>
</template>

// student-ui/src/components/sidebar/index.tsx
import { cn } from "@/utils";
import { Link } from "react-router-dom";
import SidebarItem from "./SidebarItem";
import Courses from "../../assets/sidebar/courses.svg";
import Leaderboard from "../../assets/sidebar/leaderboard.svg";
import Learn from "../../assets/sidebar/learn.svg";
import Quests from "../../assets/sidebar/quests.svg";
import { RootProps, useRoot } from "@/providers/RootProvider";
type Props = {
  className?: string;
};
const data: Parameters<typeof SidebarItem>[number][] = [
  {
    href: "/courses",
    iconSrc: Courses,
    label: "Courses",
    imgAlt: "courses icon",
  },
  {
    href: "/learn",
    iconSrc: Learn,
    label: "Learn",
    imgAlt: "learn icon",
  },
  {
    href: "/leaderboard",
    iconSrc: Leaderboard,
    label: "Leaderboard",
    imgAlt: "leaderboard icon",
  },
  {
    href: "/quests",
    iconSrc: Quests,
    label: "Quests",
    imgAlt: "quests icon",
  },
];
export default function Sidebar({ className = "" }: Props) {
  // const currentCourse = { id: "1234567", label: "python" };
  const {data:{currentCourse}} = useRoot() as RootProps;
  return (
    <div
      className={cn(
        "flex h-full lg:w-[256px] py-3 lg:fixed left-0 top-0 border-slate-700 px-4 lg:border-r-2 flex-col",
        className
      )}
    >
      <Link
        to={`/learn/${currentCourse}`}
        className="py-3  tracking-tighter text-2xl mb-5 block font-semibold bg-clip-text text-transparent bg-gradient-to-r from-green-400 via-indigo-500 to-purple-500"
      >
        Code Tutor
      </Link>
      <div className="space-y-3">
        {data.map((item) => {
          if (item.label !== "Learn") {
            return <SidebarItem {...item} key={item.href} />;
          }
          return (
            <SidebarItem
              {...item}
              href={item.href + "/" + currentCourse}
              key={item.href}
            />
          );
        })}
        <SidebarItem
          href="/profile/johndoe123"
          imgAlt="profile icon"
          username="johndoe123"
          label="Profile"
        />
      </div>
    </div>
  );
}
